services:
  - type: web
    name: westonweather-proxy
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CONTACT_EMAIL
        value: discordweston@gmail.com
